# Generated by Django 2.2 on 2021-01-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_new', '0005_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='author', to='demo_new.Book'),
        ),
    ]
